const fs = require('fs');

const baseModelsFile = fs.readFileSync('data/models.json', 'utf8');
const baseData = JSON.parse(baseModelsFile);

const newModels = [
  {
    "id": "llama-3-1-8b-instant-groq",
    "name": "Llama 3.1 8B Instant (Groq)",
    "fullName": "llama-3.1-8b-instant",
    "size": "8B",
    "tier": "no-gpu",
    "vramGB": 0,
    "recommendedQuant": "API",
    "contextLength": 131072,
    "practicalRating": { "chat": 8, "writing": 8, "coding": 7, "reasoning": 7, "agents": 7 },
    "bestFor": ["chat", "agents"],
    "ollamaTag": "groq/llama-3.1-8b-instant",
    "installCommand": "ollama run groq-llama-3.1-8b",
    "modelSizeGB": 0,
    "setupComplexity": "easy",
    "beginnerFriendly": true,
    "description": "Ultra-fast inference (1000 TPS) via Groq's LPU hardware. Great for batch processing and real-time chat.",
    "toolRecommendation": "Groq Console",
    "toolRecommendationReason": "14,400 RPD free tier",
    "highlight": true
  },
  {
    "id": "llama-4-scout-groq",
    "name": "Llama 4 Scout (Groq)",
    "fullName": "llama-4-scout",
    "size": "Unknown",
    "tier": "no-gpu",
    "vramGB": 0,
    "recommendedQuant": "API",
    "contextLength": 131072,
    "practicalRating": { "chat": 9, "writing": 9, "coding": 8, "reasoning": 8, "agents": 8 },
    "bestFor": ["chat", "writing"],
    "ollamaTag": "groq/llama-4-scout",
    "installCommand": "ollama run groq-llama-4-scout",
    "modelSizeGB": 0,
    "setupComplexity": "easy",
    "beginnerFriendly": true,
    "description": "Fast inference with Llama 4 Scout. Good for fast overrides and chat.",
    "toolRecommendation": "Groq Console",
    "toolRecommendationReason": "30K TPM free tier",
    "highlight": false
  },
  {
    "id": "qwen3-32b-groq",
    "name": "Qwen3 32B (Groq)",
    "fullName": "qwen3-32b",
    "size": "32B",
    "tier": "no-gpu",
    "vramGB": 0,
    "recommendedQuant": "API",
    "contextLength": 131072,
    "practicalRating": { "chat": 10, "writing": 9, "coding": 10, "reasoning": 9, "agents": 9 },
    "bestFor": ["coding", "chat", "research"],
    "ollamaTag": "groq/qwen3-32b",
    "installCommand": "ollama run groq-qwen3-32b",
    "modelSizeGB": 0,
    "setupComplexity": "easy",
    "beginnerFriendly": true,
    "description": "Top-tier coding and bilingual model running at 600 TPS on Groq.",
    "toolRecommendation": "Groq Console",
    "toolRecommendationReason": "60 RPM free tier",
    "highlight": true
  },
  {
    "id": "llama-3-3-70b-groq",
    "name": "Llama 3.3 70B (Groq)",
    "fullName": "llama-3.3-70b",
    "size": "70B",
    "tier": "no-gpu",
    "vramGB": 0,
    "recommendedQuant": "API",
    "contextLength": 131072,
    "practicalRating": { "chat": 10, "writing": 10, "coding": 9, "reasoning": 10, "agents": 10 },
    "bestFor": ["chat", "reasoning", "agents"],
    "ollamaTag": "groq/llama-3.3-70b",
    "installCommand": "ollama run groq-llama-3.3-70b",
    "modelSizeGB": 0,
    "setupComplexity": "easy",
    "beginnerFriendly": true,
    "description": "General-purpose heavyweight model with fast batch ranking. 400 TPS.",
    "toolRecommendation": "Groq Console",
    "toolRecommendationReason": "12K TPM free tier",
    "highlight": true
  },
  {
    "id": "gpt-oss-120b-cerebras",
    "name": "GPT OSS 120B (Cerebras)",
    "fullName": "gpt-oss-120b",
    "size": "120B",
    "tier": "no-gpu",
    "vramGB": 0,
    "recommendedQuant": "API",
    "contextLength": 8192,
    "practicalRating": { "chat": 10, "writing": 10, "coding": 10, "reasoning": 10, "agents": 10 },
    "bestFor": ["reasoning", "coding", "research"],
    "ollamaTag": "cerebras/gpt-oss-120b",
    "installCommand": "ollama run cerebras-gpt-oss",
    "modelSizeGB": 0,
    "setupComplexity": "easy",
    "beginnerFriendly": true,
    "description": "Maximum speed for a large model. ~3,000 TPS on Cerebras Wafer-Scale hardware.",
    "toolRecommendation": "Cerebras Console",
    "toolRecommendationReason": "1M tokens/day",
    "highlight": true
  },
  {
    "id": "llama-3-1-8b-cerebras",
    "name": "Llama 3.1 8B (Cerebras)",
    "fullName": "llama-3.1-8b",
    "size": "8B",
    "tier": "no-gpu",
    "vramGB": 0,
    "recommendedQuant": "API",
    "contextLength": 8192,
    "practicalRating": { "chat": 8, "writing": 8, "coding": 7, "reasoning": 7, "agents": 7 },
    "bestFor": ["chat", "agents"],
    "ollamaTag": "cerebras/llama-3.1-8b",
    "installCommand": "ollama run cerebras-llama-8b",
    "modelSizeGB": 0,
    "setupComplexity": "easy",
    "beginnerFriendly": true,
    "description": "2,600+ TPS on Cerebras. Incredible for batch processing.",
    "toolRecommendation": "Cerebras Console",
    "toolRecommendationReason": "Wafer-scale speed",
    "highlight": false
  },
  {
    "id": "deepseek-r1-openrouter",
    "name": "DeepSeek R1 (OpenRouter)",
    "fullName": "deepseek/deepseek-r1",
    "size": "Unknown",
    "tier": "no-gpu",
    "vramGB": 0,
    "recommendedQuant": "API",
    "contextLength": 131072,
    "practicalRating": { "chat": 9, "writing": 8, "coding": 10, "reasoning": 10, "agents": 9 },
    "bestFor": ["reasoning", "coding", "research"],
    "ollamaTag": "openrouter/deepseek-r1",
    "installCommand": "ollama run openrouter-deepseek-r1",
    "modelSizeGB": 0,
    "setupComplexity": "easy",
    "beginnerFriendly": true,
    "description": "Top-tier reasoning model with visible Chain of Thought. Excellent for RLHF ranking and failure taxonomy.",
    "toolRecommendation": "OpenRouter",
    "toolRecommendationReason": "Standardized API with failover",
    "highlight": true
  },
  {
    "id": "gemini-2-5-flash",
    "name": "Gemini 2.5 Flash",
    "fullName": "gemini-2.5-flash",
    "size": "Unknown",
    "tier": "no-gpu",
    "vramGB": 0,
    "recommendedQuant": "API",
    "contextLength": 1000000,
    "practicalRating": { "chat": 9, "writing": 9, "coding": 9, "reasoning": 8, "agents": 9 },
    "bestFor": ["chat", "research", "multimodal"],
    "ollamaTag": "google/gemini-2.5-flash",
    "installCommand": "ollama run google-gemini-flash",
    "modelSizeGB": 0,
    "setupComplexity": "easy",
    "beginnerFriendly": true,
    "description": "Native search grounding, 1M context, and excellent multimodal capabilities.",
    "toolRecommendation": "Google AI Studio",
    "toolRecommendationReason": "1,500 req/day",
    "highlight": true
  },
  {
    "id": "nex-n2-pro-siliconflow",
    "name": "Nex-N2-Pro (SiliconFlow)",
    "fullName": "nex-n2-pro",
    "size": "Unknown",
    "tier": "no-gpu",
    "vramGB": 0,
    "recommendedQuant": "API",
    "contextLength": 131072,
    "practicalRating": { "chat": 8, "writing": 8, "coding": 8, "reasoning": 8, "agents": 7 },
    "bestFor": ["chat"],
    "ollamaTag": "siliconflow/nex-n2-pro",
    "installCommand": "ollama run sf-nex-n2",
    "modelSizeGB": 0,
    "setupComplexity": "easy",
    "beginnerFriendly": true,
    "description": "Effectively $0/M tokens on SiliconFlow. Good for basic screening and chat.",
    "toolRecommendation": "SiliconFlow",
    "toolRecommendationReason": "Free screening",
    "highlight": false
  },
  {
    "id": "nvidia-nemotron-ultra",
    "name": "NVIDIA Nemotron Ultra 253B",
    "fullName": "nvidia/nemotron-ultra",
    "size": "253B",
    "tier": "no-gpu",
    "vramGB": 0,
    "recommendedQuant": "API",
    "contextLength": 1000000,
    "practicalRating": { "chat": 9, "writing": 9, "coding": 10, "reasoning": 10, "agents": 9 },
    "bestFor": ["reasoning", "coding"],
    "ollamaTag": "openrouter/nemotron-ultra",
    "installCommand": "ollama run or-nemotron",
    "modelSizeGB": 0,
    "setupComplexity": "easy",
    "beginnerFriendly": true,
    "description": "1M context window, high-quality reasoning, especially strong in cybersecurity eval.",
    "toolRecommendation": "OpenRouter",
    "toolRecommendationReason": "1M context",
    "highlight": true
  }
];

// Append to the existing 15 models
baseData.models = baseData.models.concat(newModels);

fs.writeFileSync('data/models_compendium.json', JSON.stringify(baseData, null, 2));
console.log('Successfully generated data/models_compendium.json with ' + baseData.models.length + ' models.');
